"""Initial tables

Revision ID: 526ceb59e5f1
Revises: 
Create Date: 2026-07-01 21:44:21.101811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526ceb59e5f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('review_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('pr_title', sa.String(length=500), nullable=False),
    sa.Column('pr_author', sa.String(length=100), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('base_branch', sa.String(length=100), nullable=False),
    sa.Column('head_branch', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index('idx_commit_sha', 'reviews', ['commit_sha'], unique=False)
    op.create_index('idx_created_at', 'reviews', ['created_at'], unique=False)
    op.create_index('idx_repo_pr', 'reviews', ['repository', 'pr_number'], unique=False)
    op.create_index('idx_timestamp', 'reviews', ['timestamp'], unique=False)
    op.create_table('agent_executions',
    sa.Column('execution_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('review_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('execution_time', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.review_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index('idx_agent_name', 'agent_executions', ['agent_name'], unique=False)
    op.create_index('idx_agent_review', 'agent_executions', ['review_id', 'agent_name'], unique=False)
    op.create_index('idx_success', 'agent_executions', ['success'], unique=False)
    op.create_table('findings',
    sa.Column('finding_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('review_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('agent_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.review_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index('idx_agent_source', 'findings', ['agent_source'], unique=False)
    op.create_index('idx_category', 'findings', ['category'], unique=False)
    op.create_index('idx_file_path', 'findings', ['file_path'], unique=False)
    op.create_index('idx_review_id', 'findings', ['review_id'], unique=False)
    op.create_index('idx_severity', 'findings', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_severity', table_name='findings')
    op.drop_index('idx_review_id', table_name='findings')
    op.drop_index('idx_file_path', table_name='findings')
    op.drop_index('idx_category', table_name='findings')
    op.drop_index('idx_agent_source', table_name='findings')
    op.drop_table('findings')
    op.drop_index('idx_success', table_name='agent_executions')
    op.drop_index('idx_agent_review', table_name='agent_executions')
    op.drop_index('idx_agent_name', table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index('idx_timestamp', table_name='reviews')
    op.drop_index('idx_repo_pr', table_name='reviews')
    op.drop_index('idx_created_at', table_name='reviews')
    op.drop_index('idx_commit_sha', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
